[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
cargo-tarpaulin = "0.26.1"
clippy = "0.0.302"
rustfmt = "0.10.0"
