name: Continuous integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI dependencies
        run: cargo install cargo-tarpaulin 
          && rustup component add clippy 
          && rustup component add rustfmt
          && cargo install cargo-audit
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test
      - name: Code Coverage
        run: cargo tarpaulin --ignore-tests
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Formatting
        run: cargo fmt -- --check
      - name: Security Check
        run: cargo audit
